# https://docs.rubocop.org/rubocop/index.html
AllCops:
  TargetRubyVersion: 3.X
  NewCops: enable

# https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainarrayliteral
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

# https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainhashliteral
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

# https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# https://docs.rubocop.org/rubocop/cops_style.html#stylestringliteralsininterpolation
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentationmethod
Style/DocumentationMethod:
  Enabled: false
  RequireForNonPublicMethods: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylemodulefunction
Style/ModuleFunction:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylemethodcallwithargsparentheses
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutparameteralignment
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirsthashelementindentation
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutfirstarrayelementindentation
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutlinelength
Layout/LineLength:
  Max: 140

# https://docs.rubocop.org/rubocop/cops_naming.html#namingmethodparametername
Naming/MethodParameterName:
  MinNameLength: 1

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/MethodLength:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize
Metrics/AbcSize:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsparameterlists
Metrics/ParameterLists:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsclasslength
Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 300

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricscyclomaticcomplexity
Metrics/CyclomaticComplexity:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsperceivedcomplexity
Metrics/PerceivedComplexity:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
Metrics/BlockLength:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmodulelength
Metrics/ModuleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
